### ISSUE TITLE
绘图失败

### ISSUE THREAD

**Issue by FesonX** [Seedarchangel/TuChart#16]
但是每次启动都是第一次显示的绘制万科的数据，go back之后，要么绘制失败显示空白，要么是显示核心已转储
具体错误如下：

- 安装及运行步骤参照的是你的文档，conda版本是4.3

> [Getting data:]Traceback (most recent call last):
  File "/home/ros/anaconda2/lib/python2.7/site-packages/Tuchart/main.py", line 352, in classify
    graphpage(labels, startdate,enddate,option,width, height)#labels:复权ork线or分笔 option:hfq, qfq or 15, 30, D, etc
  File "/home/ros/anaconda2/lib/python2.7/site-packages/Tuchart/Graph.py", line 31, in graphpage
    a = generateline(j[1],j[2],startdate,enddate,option)#stock number, Type, startdate, enddate, 30 or 15 or days
  File "/home/ros/anaconda2/lib/python2.7/site-packages/Tuchart/Graph.py", line 317, in generateline
    Open = array["open"].tolist()
  File "/home/ros/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/home/ros/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/home/ros/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/home/ros/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/home/ros/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'open'
已放弃 (核心已转储)

**Comment by Seedarchangel** [comment]
画任意图片都会产生这个错误吗？ @FesonX
