### ISSUE TITLE
运行出现错误, 显示module未找到

### ISSUE THREAD

**Issue by tommyxps** [Seedarchangel/TuChart#21]
所有的dependency 都装好了, 在python2 下运行, 出现以下提示:

c:\Users\tommy\Anaconda3\Lib\site-packages\Tuchart>python main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from Graph import graphpage
  File "c:\Users\tommy\Anaconda3\Lib\site-packages\Tuchart\Graph.py", line 3, in <module>
    from pyecharts import Kline, Line, Page,Overlap,Bar,Pie,Timeline
  File "C:\Users\tommy\Anaconda3\lib\site-packages\pyecharts\__init__.py", line 10, in <module>
    from pyecharts.charts.effectscatter import EffectScatter
  File "C:\Users\tommy\Anaconda3\lib\site-packages\pyecharts\charts\effectscatter.py", line 4, in <module>
    from pyecharts.charts.scatter import Scatter
  File "C:\Users\tommy\Anaconda3\lib\site-packages\pyecharts\charts\scatter.py", line 4, in <module>
    from PIL import Image
  File "C:\Users\tommy\Anaconda3\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.\

请问什么原因,是哪个包没有装么?

**Comment by Seedarchangel** [comment]
你似乎是在anaconda 3下跑的Tuchart, 用的还是python3.
切成anaconda 2试试？
