### ISSUE TITLE
Error when running pip install tuchart

### ISSUE THREAD

**Issue by jafetmorales** [Seedarchangel/TuChart#24]
This is the output when running <code>pip install tuchart</code>
```
Collecting tuchart
  Downloading https://files.pythonhosted.org/packages/29/7b/98e22f98a774a8e19b1b82f376f02d73013dbaaf581966627172fa17a736/tuchart-0.1.2.7-py2.py3-none-any.whl
Collecting qtpy (from tuchart)
  Downloading https://files.pythonhosted.org/packages/8a/d1/f7a708cfd4171b04196607274371d343ba84af2e39be22f310d1ec4ed91e/QtPy-1.4.2-py2.py3-none-any.whl
Collecting pyecharts==0.2.0 (from tuchart)
  Downloading https://files.pythonhosted.org/packages/da/9a/ada963b81d1608c5a195fe2a9dcbe2028ed8ac1c492a631c28c2a9cdcbb6/pyecharts-0.2.0.tar.gz (1.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uyek8e91\pyecharts\setup.py", line 7, in <module>
        from jupyterpip import cmdclass
    ImportError: No module named 'jupyterpip'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uyek8e91\pyecharts\setup.py", line 12, in <module>
        pip.main(['install', 'jupyter-pip'])
    AttributeError: module 'pip' has no attribute 'main'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-uyek8e91\pyecharts\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by lhuizhan** [comment]
Same issue here, I've tried installing it under python3 folder but got an error like this.
Working under Python 3.7.4 and Win10.

```
C:\Users\lhuiz\AppData\Local\Programs\Python\Python37-32\TuChart-master>py` setup.py install
running install
running bdist_egg
running egg_info
writing tuchart.egg-info\PKG-INFO
writing dependency_links to tuchart.egg-info\dependency_links.txt
writing requirements to tuchart.egg-info\requires.txt
writing top-level names to tuchart.egg-info\top_level.txt
reading manifest file 'tuchart.egg-info\SOURCES.txt'
writing manifest file 'tuchart.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\Graph.py -> build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\layout.py -> build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\main.py -> build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\__init__.py -> build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\__main__.py -> build\bdist.win-amd64\egg\Tuchart
copying build\lib\Tuchart\__version__.py -> build\bdist.win-amd64\egg\Tuchart
byte-compiling build\bdist.win-amd64\egg\Tuchart\Graph.py to Graph.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\Tuchart\layout.py to layout.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\Tuchart\main.py to main.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\Tuchart\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\Tuchart\__main__.py to __main__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\Tuchart\__version__.py to __version__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying tuchart.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying tuchart.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tuchart.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tuchart.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tuchart.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
Tuchart.__pycache__.main.cpython-37: module references __file__
creating 'dist\tuchart-0.1.2.5-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing tuchart-0.1.2.5-py3.7.egg
removing 'd:\users\lhuiz\anaconda3\lib\site-packages\tuchart-0.1.2.5-py3.7.egg' (and everything under it)
creating d:\users\lhuiz\anaconda3\lib\site-packages\tuchart-0.1.2.5-py3.7.egg
Extracting tuchart-0.1.2.5-py3.7.egg to d:\users\lhuiz\anaconda3\lib\site-packages
tuchart 0.1.2.5 is already the active version in easy-install.pth

Installed d:\users\lhuiz\anaconda3\lib\site-packages\tuchart-0.1.2.5-py3.7.egg
Processing dependencies for tuchart==0.1.2.5
Searching for tushare
Reading https://pypi.org/simple/tushare/
Download error on https://pypi.org/simple/tushare/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'tushare' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for tushare
error: Could not find suitable distribution for Requirement.parse('tushare')
```
The installation seems fine but then dependency setting fails.

**Comment by jafetmorales** [comment]
@Seedarchangel My computer was testing your software with Python 3.5.
